import { StyleSheet } from '@react-pdf/renderer';
import {
  COLOR_PDF,
  ESTILO_FUENTE,
  FUENTE_PDF,
  MEDIDA_FICHA,
  PESO_FUENTE,
  TAMANO_TEXTO,
} from '../plantilla/tokens';

const recuadro = { borderRadius: MEDIDA_FICHA.radioRecuadro, overflow: 'hidden' } as const;

const vacio = {
  ...recuadro,
  alignItems: 'center',
  justifyContent: 'center',
  borderWidth: MEDIDA_FICHA.borde,
  borderStyle: 'dashed',
  borderColor: COLOR_PDF.linea,
  backgroundColor: COLOR_PDF.papelHundido,
} as const;

export const fichaStyles = StyleSheet.create({
  ficha: {
    borderWidth: MEDIDA_FICHA.borde,
    borderColor: COLOR_PDF.linea,
    borderRadius: MEDIDA_FICHA.radio,
    paddingVertical: MEDIDA_FICHA.rellenoVertical,
    paddingHorizontal: MEDIDA_FICHA.rellenoHorizontal,
    marginBottom: MEDIDA_FICHA.separacion,
  },
  superior: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: MEDIDA_FICHA.aireSuperior,
    marginBottom: MEDIDA_FICHA.separacionSuperior,
    borderBottomWidth: MEDIDA_FICHA.borde,
    borderBottomColor: COLOR_PDF.linea,
  },
  especie: { flex: 1, paddingRight: MEDIDA_FICHA.hueco },
  filaEspecie: { flexDirection: 'row', alignItems: 'center' },
  punto: {
    width: MEDIDA_FICHA.punto,
    height: MEDIDA_FICHA.punto,
    borderRadius: MEDIDA_FICHA.punto / 2,
    marginRight: MEDIDA_FICHA.aireTrasPunto,
  },
  nombreEspecie: {
    fontWeight: PESO_FUENTE.semibold,
    fontSize: TAMANO_TEXTO.especie,
    color: COLOR_PDF.tinta,
  },
  sinIdentificar: { color: COLOR_PDF.ambarTexto },
  cientifico: {
    fontStyle: ESTILO_FUENTE.italica,
    fontSize: TAMANO_TEXTO.cientifico,
    color: COLOR_PDF.cuerpo,
  },
  clasificacion: {
    fontSize: TAMANO_TEXTO.clasificacion,
    color: COLOR_PDF.apagado,
    textTransform: 'uppercase',
    letterSpacing: MEDIDA_FICHA.espaciadoMayusculas,
  },
  identificador: { alignItems: 'flex-end', flexShrink: 0, maxWidth: '55%' },
  idArbol: {
    fontFamily: FUENTE_PDF.mono,
    fontWeight: PESO_FUENTE.medio,
    fontSize: TAMANO_TEXTO.idArbol,
    color: COLOR_PDF.navy,
    textAlign: 'right',
    lineHeight: 1.2,
  },
  idGlobal: { fontSize: TAMANO_TEXTO.secundario, color: COLOR_PDF.apagado, marginTop: 1 },
  idGlobalNumero: { fontFamily: FUENTE_PDF.mono, color: COLOR_PDF.cuerpo },
  marca: {
    marginTop: 2,
    paddingVertical: MEDIDA_FICHA.rellenoMarca.vertical,
    paddingHorizontal: MEDIDA_FICHA.rellenoMarca.horizontal,
    borderRadius: MEDIDA_FICHA.radioRecuadro,
    borderWidth: MEDIDA_FICHA.bordeFino,
    borderColor: COLOR_PDF.ambar,
    backgroundColor: COLOR_PDF.ambarFondo,
  },
  marcaTexto: {
    fontWeight: PESO_FUENTE.semibold,
    fontSize: TAMANO_TEXTO.marca,
    color: COLOR_PDF.ambarTexto,
    textTransform: 'uppercase',
    letterSpacing: MEDIDA_FICHA.espaciadoMayusculas,
  },
  cuerpo: { flexDirection: 'row', alignItems: 'flex-start' },
  foto: { ...recuadro, width: MEDIDA_FICHA.anchoFoto, height: MEDIDA_FICHA.altoFoto },
  fotoVacia: { ...vacio, width: MEDIDA_FICHA.anchoFoto, height: MEDIDA_FICHA.altoFoto },
  textoVacio: { fontSize: TAMANO_TEXTO.secundario, color: COLOR_PDF.tenue },
  datos: { flex: 1, marginHorizontal: MEDIDA_FICHA.hueco },
  filaDato: { flexDirection: 'row', marginBottom: MEDIDA_FICHA.separacionDatos },
  etiqueta: {
    width: MEDIDA_FICHA.anchoEtiqueta,
    paddingTop: 1,
    fontSize: TAMANO_TEXTO.etiqueta,
    color: COLOR_PDF.apagado,
    textTransform: 'uppercase',
    letterSpacing: MEDIDA_FICHA.espaciadoMayusculas,
  },
  valor: { flex: 1, fontSize: TAMANO_TEXTO.dato, color: COLOR_PDF.tinta, lineHeight: 1.35 },
  codigo: { fontFamily: FUENTE_PDF.mono, fontSize: TAMANO_TEXTO.datoMono, color: COLOR_PDF.navy },
  mono: { fontFamily: FUENTE_PDF.mono, fontSize: TAMANO_TEXTO.datoMono },
  apagado: { color: COLOR_PDF.apagado },
  tenue: { color: COLOR_PDF.tenue },
  mapa: {
    ...recuadro,
    width: MEDIDA_FICHA.ladoMapa,
    height: MEDIDA_FICHA.ladoMapa,
    borderWidth: MEDIDA_FICHA.bordeFino,
    borderColor: COLOR_PDF.linea,
  },
  mapaVacio: { ...vacio, width: MEDIDA_FICHA.ladoMapa, height: MEDIDA_FICHA.ladoMapa },
});
